include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
 rules:
  avoid_print: false
  omit_local_variable_types: false
  lines_longer_than_80_chars: false
  sort_constructors_first: false
  avoid_catches_without_on_clauses: false